name: 'Allure Report with history per branch'
description: 'Generate Allure Report with history per branch'
author: 'mgrybyk'
branding:
  icon: 'monitor'
  color: 'gray-dark'
inputs:
  report_dir:
    description: 'Input allure results dir, default "allure-results"'
    required: true
    default: 'allure-results'
  report_id:
    description: 'Output allure report dir, default "allure-report"'
    required: true
    default: 'allure-report'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
outputs:
  report_url:
    description: 'Published Allure Report url'
runs:
  using: 'docker'
  image: 'Dockerfile'
